### ISSUE TITLE
Intraday vs daily tables?

### ISSUE THREAD

**Issue by ghost** [coding-is-for-losers/ga4-bigquery-starter#3]
When I remove this line it works like a charm:
`{% set intraday_tables = dbt_utils.get_column_values(table=ref('intraday_tables_proc'), column='creation_time', max_records=1) %}`

Error message:
`Found 3 models, 1 test, 0 snapshots, 0 analyses, 283 macros, 0 operations, 0 seed files, 0 sources`
`14:28:45 | Concurrency: 1 threads (target='default')`
`14:28:46 | Finished running 2 incremental models in 0.66s.`
`Completed with 1 error and 0 warnings:`
`'NoneType' object has no attribute 'lower'`

`Done. PASS=0 WARN=0 ERROR=1 SKIP=1 TOTAL=2`

**Comment by codingisforlosers** [comment]
@jhnvdw curious if your project has `_intraday` tables, daily, or both?

**Comment by ghost** [comment]
I have both. Depends on your settings in GA property > Admin > BigQuery Linking. If both checkboxes (`Daily` and `Streaming`) are checked, you should have both.

See: https://support.google.com/analytics/answer/7029846?hl=en&ref_topic=9359001

> Within each dataset, a table is imported for each day of export. These tables have the format "events_YYYYMMDD".
> Additionally, a table is imported for app events received throughout the current day. This table is named
> “events_intraday_YYYYMMDD" and it is populated in real-time as app events are collected.

**Comment by codingisforlosers** [comment]
Yep makes sense - maybe we should flip the IF statement here then?

If daily exists, use daily, if not, use intraday.

**Comment by codingisforlosers** [comment]
FYI pushed this fix (https://github.com/coding-is-for-losers/ga4-bigquery-starter/commit/3efa14a16c0a363c7dbba344ba135e4695d1e178) for the error you mentioned, was being too cute w/ dbt ephemerality.

**Comment by ghost** [comment]
Why would you only want intraday data (current day) and not historical data (daily tables)? I'd say: if intraday exists, use daily **and** intraday, if not, use daily only.

This way you can set hourly triggers if you want near realtime data (including current date) or daily if you only need completed days.

I think we don't need that if statement logic at all. I'll push another PR as a possible solution.

**Comment by codingisforlosers** [comment]
Thanks, moving over to your PR for comment threads

**Comment by codingisforlosers** [comment]
Closing with PR #9
